### ISSUE TITLE
При вызове метода containsGame возвращается False даже при наличие игры в коллекции

### ISSUE THREAD

**Issue by RavenRVS** [RavenRVS/QAI_TeamProject#1]
# Описание
При вызове метода containsGame возвращается False даже при наличие игры в коллекции

# Локация дефекта
https://github.com/RavenRVS/QAI_TeamProject/blob/c7d6263186d4b94391ddc4dbf825c235a14c1912/src/main/java/ru/netology/GameStore.java#L32-L39

# Шаги воспроизведения
1. Открыть [проект](https://github.com/RavenRVS/QAI_TeamProject.git) в IDEA
2. Запустить тест [shouldAddGame](https://github.com/RavenRVS/QAI_TeamProject/blob/c7d6263186d4b94391ddc4dbf825c235a14c1912/src/test/java/ru/netology/GameStoreTest.java#L8-L15) в файле [GameStoreTest](https://github.com/RavenRVS/QAI_TeamProject/blob/c7d6263186d4b94391ddc4dbf825c235a14c1912/src/test/java/ru/netology/GameStoreTest.java)
3. Посмотреть вывод в консоли

*Ожидаемый результат:* Тест успешно завершен
*Фактический результат:* Тест завершен с ошибкой 

# Скриншот
![2022-10-06_15-27-23](https://user-images.githubusercontent.com/83873532/194312730-8ee17748-b3a8-4109-8dec-7d7b0690a1bb.png)

# Окружение
* **Операционная система:** Windows 11
* **IDE:** IntelliJ IDEA 2020.2 (Community Edition)
* **Java:** OpenJDK 11

# Дополнительная информация
Вероятнее всего ошибка в условии:
https://github.com/RavenRVS/QAI_TeamProject/blob/c7d6263186d4b94391ddc4dbf825c235a14c1912/src/main/java/ru/netology/GameStore.java#L33
При размере списка равного 1, условие i < games.size() не выполняется

**Comment by Luchezarnaya79** [comment]
исправлено
