### ISSUE TITLE
Метод addPlayTime не суммирует время игры 

### ISSUE THREAD

**Issue by RavenRVS** [RavenRVS/QAI_TeamProject#3]
# Описание
При добавлении времени игры по существующему ключу в словаре с помощью метода addPlayTime не выполняется суммирование времени для этого ключа.

# Локация дефекта
https://github.com/RavenRVS/QAI_TeamProject/blob/5c1665c5dbbbf79598a162c639b912ad681b4221/src/main/java/ru/netology/GameStore.java#L50-L56

# Шаги воспроизведения
1. Открыть [проект](https://github.com/RavenRVS/QAI_TeamProject.git) в IDEA
2. Запустить тест [addPlayTimeWithSumHours](https://github.com/RavenRVS/QAI_TeamProject/blob/5c1665c5dbbbf79598a162c639b912ad681b4221/src/test/java/ru/netology/GameStoreTest.java#L38-L50) в файле [GameStoreTest](https://github.com/RavenRVS/QAI_TeamProject/blob/master/src/test/java/ru/netology/GameStoreTest.java)
3. Посмотреть вывод в консоли

*Ожидаемый результат:* Тест успешно завершен
*Фактический результат:* Тест завершен с ошибкой 

# Скриншот
![2022-10-17_18-42-39](https://user-images.githubusercontent.com/83873532/196222453-88dabc79-48b5-4727-bf4f-1a6deb2eb4a9.png)

# Окружение
* **Операционная система:** Windows 11
* **IDE:** IntelliJ IDEA 2020.2 (Community Edition)
* **Java:** OpenJDK 11

# Дополнительная информация
Вероятнее всего ошибка в строке:
https://github.com/RavenRVS/QAI_TeamProject/blob/5c1665c5dbbbf79598a162c639b912ad681b4221/src/main/java/ru/netology/GameStore.java#L52
Не выполняется суммирование полученного из словаря времени с временем переданным в параметре hours

**Comment by Luchezarnaya79** [comment]
Исправлено
