### ISSUE TITLE
Метод getSumPlayedTime возвращает 0 вне зависимости от количества записей в словаре playedTime

### ISSUE THREAD

**Issue by RavenRVS** [RavenRVS/QAI_TeamProject#5]
# Описание
При вызове метода getSumPlayedTime вместо суммарного времени игры всех игроков в словаре playedTime всегда возвращается 0

# Локация дефекта
https://github.com/RavenRVS/QAI_TeamProject/blob/5c1665c5dbbbf79598a162c639b912ad681b4221/src/main/java/ru/netology/GameStore.java#L79-L81

# Шаги воспроизведения
1. Открыть [проект](https://github.com/RavenRVS/QAI_TeamProject.git) в IDEA
2. Запустить тест [getSumPlayedTime](https://github.com/RavenRVS/QAI_TeamProject/blob/5c1665c5dbbbf79598a162c639b912ad681b4221/src/test/java/ru/netology/GameStoreTest.java#L89-L100) в файле [GameStoreTest](https://github.com/RavenRVS/QAI_TeamProject/blob/c7d6263186d4b94391ddc4dbf825c235a14c1912/src/test/java/ru/netology/GameStoreTest.java)
3. Посмотреть вывод в консоли

*Ожидаемый результат:* Тест успешно завершен
*Фактический результат:* Тест завершен с ошибкой 

# Скриншот
![2022-10-18_11-09-02](https://user-images.githubusercontent.com/83873532/196373705-e2991ea1-6aa0-4ac7-8189-a7e654aafb85.png)

# Окружение
* **Операционная система:** Windows 11
* **IDE:** IntelliJ IDEA 2020.2 (Community Edition)
* **Java:** OpenJDK 11

# Дополнительная информация
Вероятнее всего ошибка в условии:
https://github.com/RavenRVS/QAI_TeamProject/blob/5c1665c5dbbbf79598a162c639b912ad681b4221/src/main/java/ru/netology/GameStore.java#L80
В методе отсутствует код обработки данных из словаря playedTime.

**Comment by Luchezarnaya79** [comment]
Исправлено
